version: '3.9'
volumes:
  postgres_volume:
services:
  postgres:
    image: postgres:14-alpine3.17
    container_name: postgres
    env_file:
      - ./config/.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    networks:
      - authnet
  auth:
    image: auth
    container_name: auth
    build:
      context: .
      dockerfile: auth.Dockerfile
    env_file:
      - ./config/.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      authnet:
        ipv4_address: 172.19.0.4
  migrator:
    image: migrator
    container_name: migrator
    build:
      context: .
      dockerfile: migrator.Dockerfile
    restart: on-failure
    env_file:
      - ./config/.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - authnet
networks:
  authnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
